Silhouette added
Jonnix12/Tzipory pull request #5
Opened 2023-08-23 14:49 UTC by AlonsHub

Important to create obstacles manually with a 2d polygon collider.

Just add the 2d poly collider component on the same object as the obstacles SpriteRenderer

2023-08-23 15:16 UTC, Jonnix12 requested changes
Hi, I've added comments, I'd love for you to go through them and update me

2023-08-23 15:16 UTC, Jonnix12 commented on Assets/OnValidate_SeeThroughMaskFixer.cs
The names of the variables need to be like specified in the dev bible, It is important to maintain consistency.
Add private before private variables

2023-08-23 15:16 UTC, Jonnix12 commented on Assets/Scripts/Systems/EntitySystem/BaseUnitEntity.cs
We have already discussed it, and it was possible to remove the change from baseUnitEntity to a separate script, at the moment we will have a conflict, but I hope to try to avoid this

2023-08-24 07:33 UTC, Jonnix12 requested changes
Good job, a few small things and we'll be done.

2023-08-24 07:33 UTC, Jonnix12 commented on Assets/Obstacle_ZSetter.cs
> +    Silhouetter _silhouetter;
Need to add Explicit private

2023-08-24 07:33 UTC, Jonnix12 commented on Assets/Scripts/Testing/Silhouetter.cs
Need to move the script in to a relevant folder

2023-08-24 07:33 UTC, Jonnix12 commented on Assets/Obstacle_ZSetter.cs
Need to move the script to a relevant folder

2023-08-31 09:50 UTC, AlonsHub commented on Assets/Scripts/Testing/Silhouetter.cs
Moved to new Folder GraphicsSystems

Generally, GraphicsSystems takes all sorts of scripts that have to do with how the game looks and behaves visually

2023-08-31 09:50 UTC, AlonsHub commented on Assets/Obstacle_ZSetter.cs
Also moved to new Folder GraphicsSystems

2023-09-04 09:38 UTC, Jonnix12 submitted a review, later dismissed

2023-09-19 11:26 UTC, closed without merging